import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Image Optimization</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Image Optimization Using<a href="https://nextjs.org">Next.js!</a>
        </h1>

      

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
          <img src="/snow1.jpg"/>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
             
          <Image src="/snow2.jpg" width={300} height={200}/>
          </a>

         
        </div>
      </main>

    </div>
  )
}
