export const INC_COUNTER="INC_COUNTER"
export const DEC_COUNTER="DEC_COUNTER"
export const ADD_TODO="ADD_TODO"


export const ADD_TOOD_REQ=" ADD_TOOD_REQ"

export const ADD_TOOD_SUCCESS=" ADD_TOOD_SUCCESS"

export const ADD_TOOD_FAILURE=" ADD_TOOD_FAILURE"