import Head from 'next/head'
import Image from 'next/image'
import Link from "next/link"
import Navbar from '../component/Navbar'
import styles from '../styles/Home.module.css'

export const getStaticProps = async()=>{
  const res= await fetch('https://reqres.in/api/users')
  const data =await res.json();

  return {
    props:{
      data,
    }
  }
}





export default function Home({data}) {

 



  return (
    <div>
      <Head>
        <title>Uers List</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      
       <Navbar/>
     {
       data.data.map((el)=><Link href={`/users/${el.id}`}><div className={styles.userDiv}>
         
         <h1>{el.id}</h1>
         <h1>{el.first_name}</h1>
       </div>
       </Link>
       )
     }

      
    </div>
  )
}
